"""dbt assets for taxiflow.

Uses dagster-dbt to automatically create assets from dbt models.
Each dbt model becomes a Dagster asset with proper dependencies.
"""

from pathlib import Path

from dagster import AssetExecutionContext
from dagster_dbt import DbtCliResource, dbt_assets, DagsterDbtTranslator

from ..resources import dbt_resource


# path to dbt project
DBT_PROJECT_DIR = Path(__file__).parent.parent.parent

# path to dbt manifest (generated by dbt parse or dbt compile)
DBT_MANIFEST_PATH = DBT_PROJECT_DIR / "target" / "manifest.json"


class TaxiflowDbtTranslator(DagsterDbtTranslator):
    """Custom translator to configure how dbt models appear in Dagster."""

    def get_group_name(self, dbt_resource_props: dict) -> str:
        """Group dbt models by their schema/folder."""
        # use the dbt model's folder as the group name
        fqn = dbt_resource_props.get("fqn", [])
        if len(fqn) >= 2:
            # fqn is like ["taxiflow", "staging", "stg_yellow_trips"]
            return fqn[1]  # returns "staging", "intermediate", etc.
        return "dbt"

    def get_description(self, dbt_resource_props: dict) -> str:
        """Use dbt model description if available."""
        return dbt_resource_props.get("description", "")


@dbt_assets(
    manifest=DBT_MANIFEST_PATH,
    dagster_dbt_translator=TaxiflowDbtTranslator(),
)
def dbt_taxiflow_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    """All dbt models as Dagster assets.

    This automatically creates an asset for each dbt model, seed, and snapshot.
    Dependencies between models are preserved from the dbt DAG.

    The assets are grouped by their dbt folder:
    - staging: raw data cleaning and standardization
    - intermediate: business logic and unions
    - dimensions: dimension tables for the star schema
    - facts: fact tables with measures
    - marts: aggregated tables for reporting
    """
    yield from dbt.cli(["build"], context=context).stream()
