"""dbt assets for taxiflow."""

from pathlib import Path

from dagster import AssetExecutionContext
from dagster_dbt import DbtCliResource, dbt_assets, DagsterDbtTranslator

from ..resources import dbt_resource


# path to dbt project
DBT_PROJECT_DIR = Path(__file__).parent.parent.parent

# path to dbt manifest (generated by dbt parse or dbt compile)
DBT_MANIFEST_PATH = DBT_PROJECT_DIR / "target" / "manifest.json"


class TaxiflowDbtTranslator(DagsterDbtTranslator):
    """Custom translator to configure how dbt models appear in Dagster."""

    def get_group_name(self, dbt_resource_props: dict) -> str:
        fqn = dbt_resource_props.get("fqn", [])
        if len(fqn) >= 2:
            return fqn[1]
        return "dbt"

    def get_description(self, dbt_resource_props: dict) -> str:
        return dbt_resource_props.get("description", "")


@dbt_assets(
    manifest=DBT_MANIFEST_PATH,
    dagster_dbt_translator=TaxiflowDbtTranslator(),
)
def dbt_taxiflow_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    """All dbt models as Dagster assets."""
    yield from dbt.cli(["build"], context=context).stream()
