"""dbt assets for taxiflow."""

from pathlib import Path

from dagster import AssetExecutionContext, AssetKey
from dagster_dbt import (
    DagsterDbtTranslator,
    DagsterDbtTranslatorSettings,
    DbtCliResource,
    dbt_assets,
)

# path to dbt project
DBT_PROJECT_DIR = Path(__file__).parent.parent.parent

# path to dbt manifest (generated by dbt parse or dbt compile)
DBT_MANIFEST_PATH = DBT_PROJECT_DIR / "target" / "manifest.json"

# the Dagster asset that downloads the TLC parquet files (see ingestion.py)
RAW_TAXI_DATA_KEY = AssetKey("raw_taxi_data")


class TaxiflowDbtTranslator(DagsterDbtTranslator):
    """Custom translator to configure how dbt models appear in Dagster."""

    def get_asset_key(self, dbt_resource_props: dict) -> AssetKey:
        # both nyc_tlc sources are files written by the one download asset, so
        # pointing them at it makes raw_taxi_data an upstream of the staging models
        if dbt_resource_props.get("resource_type") == "source":
            return RAW_TAXI_DATA_KEY
        return super().get_asset_key(dbt_resource_props)

    def get_group_name(self, dbt_resource_props: dict) -> str:
        fqn = dbt_resource_props.get("fqn", [])
        if len(fqn) >= 2:
            return fqn[1]
        return "dbt"

    def get_description(self, dbt_resource_props: dict) -> str:
        return dbt_resource_props.get("description", "")


@dbt_assets(
    manifest=DBT_MANIFEST_PATH,
    dagster_dbt_translator=TaxiflowDbtTranslator(
        # two dbt sources map to the same raw_taxi_data key on purpose
        settings=DagsterDbtTranslatorSettings(enable_duplicate_source_asset_keys=True),
    ),
)
def dbt_taxiflow_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    """All dbt models as Dagster assets."""
    yield from dbt.cli(["build"], context=context).stream()
